import type { NextPage } from "next";
import Head from "next/head";

import styled from "styled-components";

const Main = styled.main`
  background-color: #f8f8fb;
  width: 100%;
  height: 100vh;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main></Main>
    </div>
  );
};

export default Home;
